// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace nativeTrackerClientService.Entities
{
    [Table("Vehicle", Schema = "Vehicle")]
    public partial class Vehicle
    {
        public Vehicle()
        {
            Installations = new HashSet<Installation>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(64)]
        public string Name { get; set; }
        [Required]
        public byte[] Photo { get; set; }
        [Required]
        [StringLength(30)]
        public string ClientLogin { get; set; }

        [ForeignKey("ClientLogin")]
        [InverseProperty("Vehicles")]
        public virtual ClientUser ClientLoginNavigation { get; set; }
        [InverseProperty("Vehicle")]
        public virtual ICollection<Installation> Installations { get; set; }
    }
}