// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace nativeTrackerClientService.Entities
{
    [Table("ClientUser", Schema = "Client")]
    public partial class ClientUser
    {
        public ClientUser()
        {
            Vehicles = new HashSet<Vehicle>();
        }

        [Key]
        [StringLength(30)]
        public string Login { get; set; }
        [Required]
        [StringLength(64)]
        [Unicode(false)]
        public string Password { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateDate { get; set; }

        [InverseProperty("ClientLoginNavigation")]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}