// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace nativeTrackerClientService.Entities
{
    [Table("Feature", Schema = "Track")]
    public partial class Feature
    {
        public Feature()
        {
            Models = new HashSet<Model>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(64)]
        public string Name { get; set; }

        [ForeignKey("FeatureID")]
        [InverseProperty("Features")]
        public virtual ICollection<Model> Models { get; set; }
    }
}