// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace nativeTrackerClientService.Entities
{
    [Table("Installation", Schema = "Track")]
    public partial class Installation
    {
        public Installation()
        {
            InstallationAttachments = new HashSet<InstallationAttachment>();
            VehicleStates = new HashSet<VehicleState>();
        }

        [Key]
        public int IMEI { get; set; }
        public int WorkerID { get; set; }
        public int VehicleID { get; set; }
        public int ModelID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Timestamp { get; set; }
        [Required]
        [StringLength(1000)]
        public string Description { get; set; }

        [ForeignKey("ModelID")]
        [InverseProperty("Installations")]
        public virtual Model Model { get; set; }
        [ForeignKey("VehicleID")]
        [InverseProperty("Installations")]
        public virtual Vehicle Vehicle { get; set; }
        [ForeignKey("WorkerID")]
        [InverseProperty("Installations")]
        public virtual Worker Worker { get; set; }
        [InverseProperty("IMEINavigation")]
        public virtual ICollection<InstallationAttachment> InstallationAttachments { get; set; }
        [InverseProperty("IMEINavigation")]
        public virtual ICollection<VehicleState> VehicleStates { get; set; }
    }
}