// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace nativeTrackerClientService.Entities
{
    [Table("Model", Schema = "Track")]
    public partial class Model
    {
        public Model()
        {
            Installations = new HashSet<Installation>();
            Pictures = new HashSet<Picture>();
            Features = new HashSet<Feature>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(64)]
        public string Name { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Price { get; set; }
        [StringLength(1000)]
        public string Description { get; set; }

        [InverseProperty("Model")]
        public virtual ICollection<Installation> Installations { get; set; }
        [InverseProperty("Model")]
        public virtual ICollection<Picture> Pictures { get; set; }

        [ForeignKey("ModelID")]
        [InverseProperty("Models")]
        public virtual ICollection<Feature> Features { get; set; }
    }
}