// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace nativeTrackerClientService.Entities
{
    [Table("Picture", Schema = "Track")]
    public partial class Picture
    {
        [Key]
        public int ID { get; set; }
        public int ModelID { get; set; }
        [Required]
        public byte[] Data { get; set; }

        [ForeignKey("ModelID")]
        [InverseProperty("Pictures")]
        public virtual Model Model { get; set; }
    }
}