// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace nativeTrackerClientService.Entities
{
    [Table("StateType", Schema = "Track")]
    public partial class StateType
    {
        public StateType()
        {
            VehicleStates = new HashSet<VehicleState>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(20)]
        public string Name { get; set; }

        [InverseProperty("StateType")]
        public virtual ICollection<VehicleState> VehicleStates { get; set; }
    }
}