// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace nativeTrackerClientService.Entities
{
    [Table("VehicleState", Schema = "Track")]
    public partial class VehicleState
    {
        [Key]
        public int ID { get; set; }
        public int IMEI { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Timestamp { get; set; }
        public int StateTypeID { get; set; }
        [Required]
        [MaxLength(512)]
        public byte[] Data { get; set; }

        [ForeignKey("IMEI")]
        [InverseProperty("VehicleStates")]
        public virtual Installation IMEINavigation { get; set; }
        [ForeignKey("StateTypeID")]
        [InverseProperty("VehicleStates")]
        public virtual StateType StateType { get; set; }
    }
}