// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace nativeTrackerClientService.Entities
{
    [Table("Worker", Schema = "Track")]
    public partial class Worker
    {
        public Worker()
        {
            Installations = new HashSet<Installation>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(30)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(30)]
        public string LastName { get; set; }
        [StringLength(30)]
        public string Patrynomic { get; set; }
        [Required]
        public byte[] Photo { get; set; }

        [InverseProperty("Worker")]
        public virtual ICollection<Installation> Installations { get; set; }
    }
}